import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "./globals.css";
import Layout from "@/components/Layout";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "HeroTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} `}>
        <main>
          <AntdRegistry>
            <Layout>{children}</Layout>
          </AntdRegistry>
        </main>
      </body>
    </html>
  );
}
